<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="X-UA-Compatible" content="IE=edge"><meta name="google-site-verification" content="IDYUPnBNhdnU8o9LRNKZ1RSt14tIxTI0rLeMrBtswXw"><title> script error · Fish</title><meta name="description" content="script error - Fish"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="icon" href="/posts/favicon.png"><link rel="stylesheet" href="/posts/css/apollo.css"><link rel="search" type="application/opensearchdescription+xml" href="https://icyfish.github.io/posts/atom.xml" title="Fish"><meta name="generator" content="Hexo 7.0.0-rc1"></head><body><div class="wrap"><header><a href="/posts/" class="logo-link"><img src="/posts/favicon.png" alt="logo"></a><ul class="nav nav-list"><li class="nav-list-item"><a href="/posts/" target="_self" class="nav-list-link">BLOG</a></li><li class="nav-list-item"><a href="/posts/archives/" target="_self" class="nav-list-link">ARCHIVE</a></li><li class="nav-list-item"><a href="/posts/about/" target="_self" class="nav-list-link">ABOUT</a></li><li class="nav-list-item"><a href="http://twitter.com/icyfish_" target="_blank" class="nav-list-link">TWITTER</a></li></ul></header><main class="container"><div class="post"><article class="post-block"><h1 class="post-title">script error</h1><div class="post-info">Dec 25, 2017</div><div class="post-content"><p>script error 和 JavaScript 中的错误类型</p>
<a id="more"></a>
<h1 id="什么是”Script-error”"><a href="#什么是”Script-error”" class="headerlink" title="什么是”Script error”"></a>什么是”Script error”</h1><p>使用 JavaScript 的 onerror 事件处理异常, 很有可能会遇到”Script error”这样的错误. </p>
<p>“Script error”其实是由跨域的第三方JavaScript文件引起的. 这是个很令人头疼的错误, 因为尽管出现了错误, 但是我们无法得知具体是怎样的错误, 也不知道这个错误产生的位置. 这时, 就可以使用<code>window.onerror</code>来了解错误的具体信息. </p>
<h2 id="起因-跨域脚本"><a href="#起因-跨域脚本" class="headerlink" title="起因: 跨域脚本"></a>起因: 跨域脚本</h2><p>查看以下HTML代码, 假设这部分代码由是这个 <a href="http://example.com/test" target="_blank" rel="noopener">http://example.com/test</a> 网页的HTML:</p>
<figure class="highlight html"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">&lt;!doctype <span class="meta-keyword">html</span>&gt;</span></span><br><span class="line"><span class="tag">&lt;<span class="name">html</span>&gt;</span></span><br><span class="line"><span class="tag">&lt;<span class="name">head</span>&gt;</span></span><br><span class="line">  <span class="tag">&lt;<span class="name">title</span>&gt;</span>example.com/test<span class="tag">&lt;/<span class="name">title</span>&gt;</span></span><br><span class="line"><span class="tag">&lt;/<span class="name">head</span>&gt;</span></span><br><span class="line"><span class="tag">&lt;<span class="name">body</span>&gt;</span></span><br><span class="line">  <span class="tag">&lt;<span class="name">script</span> <span class="attr">src</span>=<span class="string">"http://another-domain.com/app.js"</span>&gt;</span><span class="tag">&lt;/<span class="name">script</span>&gt;</span></span><br><span class="line">  <span class="tag">&lt;<span class="name">script</span>&gt;</span></span><br><span class="line"><span class="javascript">  <span class="built_in">window</span>.onerror = <span class="function"><span class="keyword">function</span> (<span class="params">message, url, line, column, error</span>) </span>&#123;</span></span><br><span class="line"><span class="javascript">    <span class="built_in">console</span>.log(message, url, line, column, error);</span></span><br><span class="line">  &#125;</span><br><span class="line"><span class="actionscript">  foo(); <span class="comment">// call function declared in app.js</span></span></span><br><span class="line">  <span class="tag">&lt;/<span class="name">script</span>&gt;</span></span><br><span class="line"><span class="tag">&lt;/<span class="name">body</span>&gt;</span></span><br><span class="line"><span class="tag">&lt;/<span class="name">html</span>&gt;</span></span><br></pre></td></tr></table></figure>
<p>以下是 <a href="http://another-domain.com/app.js" target="_blank" rel="noopener">http://another-domain.com/app.js</a> 的内容, 只声明了一个函数 <code>foo</code>, 调用<code>foo</code>始终会抛出ReferenceError.</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// another-domain.com/app.js</span></span><br><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">foo</span>(<span class="params"></span>) </span>&#123;</span><br><span class="line">  bar(); <span class="comment">// ReferenceError: bar is not a function</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>浏览器加载HTML文档, 执行 JavaScript 文件之后, 控制台就会输出以下内容(通过<code>window.onerror</code>回调输出)</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="string">"Script error."</span>, <span class="string">""</span>, <span class="number">0</span>, <span class="number">0</span>, <span class="literal">undefined</span></span><br></pre></td></tr></table></figure>
<p>这并不是 JavaScript 的 bug, 浏览器会可以隐藏跨域脚本的错误信息以确保安全性. 这样的方式能够避免脚本不小心在onerror回调中泄露敏感信息. 因此, 只有在同域的<code>window.onerror</code>回调函数中, 才可以看到详细的错误信息, 除此之外, 只能看到”Script errpr”</p>
<p>尽管浏览器出于好意隐藏了详细错误信息, 但是有很多情况下我们需要知道跨域脚本究竟产生了怎样的错误: </p>
<ol>
<li>应用的JavaScript文件位于不同域下.</li>
<li>使用托管于CDN的库, 比如cdnjs.</li>
<li>使用商业性的第三方JavaScript库, 只存在于外部服务器.</li>
</ol>
<p>为了解决上述的问题, 必须要知道错误的详细信息, 我们只需要实行以下操作:</p>
<h2 id="解决办法-CORS属性及头部"><a href="#解决办法-CORS属性及头部" class="headerlink" title="解决办法: CORS属性及头部"></a>解决办法: CORS属性及头部</h2><p>1.添加<code>crossorigin=”anonymous”</code>到 script 标签的属性中:</p>
<figure class="highlight html"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="tag">&lt;<span class="name">script</span> <span class="attr">src</span>=<span class="string">"http://another-domain.com/app.js"</span> <span class="attr">crossorigin</span>=<span class="string">"anonymous"</span>&gt;</span><span class="tag">&lt;/<span class="name">script</span>&gt;</span></span><br></pre></td></tr></table></figure>
<p>以上属性告诉浏览器匿名获取目标文件, 这样的话, 浏览器请求该文件时, 就不会发送潜在的泄露用户资料的信息, 如cookie或HTTP认证信息. </p>
<p>2.添加支持跨域的HTTP头部</p>
<figure class="highlight ada"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">Access</span>-Control-Allow-Origin: *</span><br></pre></td></tr></table></figure>
<p>CORS指: 跨域资源共享, 由一系列的API组成(其中大部分是HTTP头部), 这些API用以说明跨域文件应该以怎样的方式被获取.</p>
<p>通过设置<code>Access-Control-Allow-Origin: *</code>. 服务器给浏览器这样的指示: 任何域名下的文件都可以获取该文件. 同样可以将<code>*</code>换成特定的域名:<br><figure class="highlight groovy"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">Access-Control-Allow-<span class="string">Origin:</span> <span class="string">https:</span><span class="comment">//www.example.com</span></span><br></pre></td></tr></table></figure></p>
<p>通过以上两步的配置, 任何由该文件引起的错误详细信息都会通过<code>window.onerror</code>的回调函数抛出, 不再是”Script error”</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="string">"ReferenceError: bar is not defined"</span>, <span class="string">"http://another-domain.com/app.js"</span>, <span class="number">2</span>, <span class="number">1</span>, [<span class="built_in">Object</span> <span class="built_in">Error</span>]</span><br></pre></td></tr></table></figure>
<h2 id="另一种解决方式-使用-try-catch"><a href="#另一种解决方式-使用-try-catch" class="headerlink" title="另一种解决方式: 使用 try/catch"></a>另一种解决方式: 使用 try/catch</h2><p>有时候, 我们没有权限修改所使用的第三方JS头部. 这样的情况下, 就得使用<code>try/catch</code>方法, 见下例, 不添加<code>crossorigin=&quot;anonymous&quot;</code></p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// &lt;!-- note: crossorigin="anonymous" intentionally absent --&gt;</span></span><br><span class="line">&lt;script src=<span class="string">"http://another-domain.com/app.js"</span>&gt;&lt;<span class="regexp">/script&gt;</span></span><br><span class="line"><span class="regexp">&lt;script&gt;</span></span><br><span class="line"><span class="regexp">window.onerror = function (message, url, line, column, error) &#123;</span></span><br><span class="line"><span class="regexp">  console.log(message, url, line, column, error);</span></span><br><span class="line"><span class="regexp">&#125;</span></span><br><span class="line"><span class="regexp"></span></span><br><span class="line"><span class="regexp">try &#123;</span></span><br><span class="line"><span class="regexp">  foo(); /</span><span class="regexp">/ call function declared in app.js</span></span><br><span class="line"><span class="regexp">&#125; catch (e) &#123;</span></span><br><span class="line"><span class="regexp">  console.log(e);</span></span><br><span class="line"><span class="regexp">  throw e; /</span><span class="regexp">/ intentionally re-throw (caught by window.onerror)</span></span><br><span class="line"><span class="regexp">&#125;</span></span><br><span class="line"><span class="regexp">&lt;/</span>script&gt;</span><br></pre></td></tr></table></figure>
<p>第三方JS文件:</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// another-domain.com/app.js</span></span><br><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">foo</span>(<span class="params"></span>) </span>&#123;</span><br><span class="line">  bar(); <span class="comment">// ReferenceError: bar is not a function</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>运行上述HTML, 会输出以下内容: </p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line">=&gt; <span class="built_in">ReferenceError</span>: bar is not defined</span><br><span class="line">     at foo (http:<span class="comment">//another-domain.com/b.js:2:3)</span></span><br><span class="line">     at http:<span class="comment">//example.com/test/:15:3</span></span><br><span class="line"></span><br><span class="line">=&gt; <span class="string">"Script error."</span>, <span class="string">""</span>, <span class="number">0</span>, <span class="number">0</span>, <span class="literal">undefined</span></span><br></pre></td></tr></table></figure>
<p>第一个输出的声明来自<code>try/catch</code>的捕获, 获得了错误对象, 含有错误类型, 错误信息以及堆栈轨迹, 包括文件名以及错误所在行号. 第二个输出的声明来自<code>window.onerror</code>的捕获, 只能够输出”Script error”, 没有其它有效信息.</p>
<p>尽管<code>try/catch</code>是一种解决办法, 但是能够修改HTML文档和CORS头部的情况下, 用<code>window.onerror</code>是更好的方式.</p>
<h1 id="JavaScript中的异常处理"><a href="#JavaScript中的异常处理" class="headerlink" title="JavaScript中的异常处理"></a><a href="https://www.sitepoint.com/exceptional-exception-handling-in-javascript/" target="_blank" rel="noopener">JavaScript中的异常处理</a></h1><p>JS代码抛出异常后, JS解释器(interpreter)会执行<a href="https://en.wikipedia.org/wiki/Exception_handling" target="_blank" rel="noopener">处理异常</a>的代码, 如果没有处理异常的代码, 应用就会在抛出异常的函数中 return. 一步步执行执行栈中的函数, 直到找到处理异常的函数或到达执行栈顶部的函数, 应用内的终止运行.</p>
<h2 id="Error-对象"><a href="#Error-对象" class="headerlink" title="Error 对象"></a>Error 对象</h2><p>当异常发生, Error 对象会被创建并抛出, JavaScript 定义了7种类型的错误对象: </p>
<h3 id="Error"><a href="#Error" class="headerlink" title="Error"></a>Error</h3><p>一般开发者自定义的异常会使用该对象, 使用以下方式定义:</p>
<p> <code>var error = new Error(&quot;error message&quot;)</code> </p>
<p><code>Error</code>对象有两个属性, name 和 message. name 指异常的类型, 此时为 Error. message 是对该错误的具体描述, 以参数形式传入, 此时是”error message”. 其他6种类型的更加具体Error对象也含有同样的这两种属性. </p>
<h3 id="RangeError"><a href="#RangeError" class="headerlink" title="RangeError"></a>RangeError</h3><p>试图传递一个number参数给一个范围内不包含该number的函数时会引发RangeError. 当传递一个不合法的length值作为Array 构造器的参数创建数组, 或者传递错误值到数值计算方法（Number.toExponential(), Number.toFixed(), Number.toPrecision()）</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">var</span> pi = <span class="number">3.14159</span></span><br><span class="line">pi.toFixed(<span class="number">10000</span>) <span class="comment">// RangeError</span></span><br></pre></td></tr></table></figure>
<h3 id="ReferenceError"><a href="#ReferenceError" class="headerlink" title="ReferenceError"></a>ReferenceError</h3><p>引用错误: 引用作用域内不存在的变量抛出的错误</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">foo</span>(<span class="params"></span>) </span>&#123;</span><br><span class="line">  bar++;  <span class="comment">// ReferenceError</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h3 id="SyntaxError"><a href="#SyntaxError" class="headerlink" title="SyntaxError"></a>SyntaxError</h3><p>语法错误: C 和 Java在编译过程中, 会抛出 Syntax Error, 但 JavaScript 作为解释性语言, 代码执行过程中才会发现Syntax Error. <code>Syntax errors are unique as they are the only type of exception that cannot be recovered from.</code></p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">if</span> (foo) &#123;  <span class="comment">// SyntaxError</span></span><br></pre></td></tr></table></figure>
<h3 id="TypeError"><a href="#TypeError" class="headerlink" title="TypeError"></a>TypeError</h3><p>当某个值并非预期的类型, 会抛出 TypeError, 这种情况常出现在调用不存在的对象方法时</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">var</span> foo = &#123;&#125;</span><br><span class="line"></span><br><span class="line">foo.bar() <span class="comment">// TypeError</span></span><br></pre></td></tr></table></figure>
<h3 id="URIError"><a href="#URIError" class="headerlink" title="URIError"></a>URIError</h3><p>encodeURI()/decodeURI() 中传入的参数格式不是合法的URI, 会抛出此错误</p>
<p><code>decodeURIComponent(&quot;%&quot;); // URIError</code></p>
<h2 id="EvalError"><a href="#EvalError" class="headerlink" title="EvalError"></a>EvalError</h2><p>不合理使用<code>eval()</code>函数, 会抛出该错误. 但在最新版本的EcmaScript标准中, 已不再使用该错误类型.</p>
<h2 id="处理异常"><a href="#处理异常" class="headerlink" title="处理异常"></a>处理异常</h2><p>JavaScript 使用 <code>try…catch…finally</code> 处理程序中的异常:</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">  <span class="comment">// 意图执行, 有可能抛出异常的代码</span></span><br><span class="line">&#125; <span class="keyword">catch</span> (exception) &#123;</span><br><span class="line">  <span class="comment">// 处理意图执行的代码抛出的异常</span></span><br><span class="line">&#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">  <span class="comment">// 始终会执行的代码</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>使用 <code>try</code> 之后必须跟上 <code>catch</code> 或者 <code>finally</code>, 或者两者均有. </p>
<h3 id="catch语句"><a href="#catch语句" class="headerlink" title="catch语句"></a><code>catch</code>语句</h3><p>尽管 <code>catch</code>是可选语句, 但是处理异常的代码本应是存在的. <code>catch</code>语句会阻止异常在调用栈中(…), 这样即使出现异常, 程序还能正常运行. propagating through the call stack. 如果<code>try</code>语句中的异常发生, 程序的控制权就转给了<code>catch</code>语句中的代码. 同时所发生的异常也被传入其中. 以下例子说明了<code>catch</code>语句是如何处理”ReferenceError”的, ReferenceError对象传入通过参数’exception’传入<code>catch</code></p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">  foo++;  <span class="comment">// ReferenceError</span></span><br><span class="line">&#125; <span class="keyword">catch</span> (exception) &#123;</span><br><span class="line">  <span class="keyword">var</span> message = exception.message;</span><br><span class="line">  <span class="comment">// 处理异常</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>复杂的程序会产生各种各样的异常, 这种情况下, 可以利用<code>instanceof</code>操作符来区分不同类型的异常. 以下例子中, 假定<code>try</code>语句中产生了多种类型的异常, 紧随其后的<code>catch</code>语句通过<code>instanceof</code>操作符区分不同的异常并对其做出相应的处理.</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">  <span class="comment">// 假定此处发生异常</span></span><br><span class="line">&#125; <span class="keyword">catch</span> (exception) &#123;</span><br><span class="line">  <span class="keyword">if</span> (exception <span class="keyword">instanceof</span> <span class="built_in">TypeError</span>) &#123;</span><br><span class="line">    <span class="comment">// 处理 TypeError 异常</span></span><br><span class="line">  &#125; <span class="keyword">else</span> <span class="keyword">if</span> (exception <span class="keyword">instanceof</span> <span class="built_in">ReferenceError</span>) &#123;</span><br><span class="line">    <span class="comment">// 处理 TypeError 异常</span></span><br><span class="line">  &#125; <span class="keyword">else</span> &#123;</span><br><span class="line">    <span class="comment">// 处理其他类型的异常</span></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h3 id="finally语句"><a href="#finally语句" class="headerlink" title="finally语句"></a><code>finally</code>语句</h3><p><code>finally</code>语句中的代码始终会执行, 常在其中加入一些总结处理的代码(例如关闭文件…). <strong>即使发生的异常没有被捕获, <code>finally</code>语句也会执行</strong>, 这种情况下, <code>finally</code>中的语句执行, <strong>然后被抛出的异常正常执行. 还有一点要注意, 即使<code>try</code>, <code>catch</code>中有<code>return</code>声明, <code>finally</code>语句也会执行.</strong> 因此以下函数返回的是<code>false</code></p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">foo</span>(<span class="params"></span>) </span>&#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="keyword">return</span> <span class="literal">true</span>;</span><br><span class="line">  &#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">    <span class="keyword">return</span> <span class="literal">false</span>;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h2 id="抛出异常"><a href="#抛出异常" class="headerlink" title="抛出异常"></a>抛出异常</h2><p>JavaScript 允许开发者抛出自定义的异常, 通过<code>throw</code>声明实现. 没有经验的开发者或许会很困惑, 一般开发者都会努力写出没有任何错误的代码, 可是<code>throw</code>声明却主动引入错误. 实际上, 这样的方式能够帮助开发者写出更加容易调试和维护的代码. 在自定义异常中抛出合理的错误信息使得问题更容易被发现和解决. </p>
<p>下面是几个<code>throw</code>声明的例子. 对于声明中抛出的异常类型和抛出次数, JavaScript都没有做出限制.</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">throw</span> <span class="literal">true</span>;</span><br><span class="line"><span class="keyword">throw</span> <span class="number">5</span>;</span><br><span class="line"><span class="keyword">throw</span> <span class="string">"error message"</span>;</span><br><span class="line"><span class="keyword">throw</span> <span class="literal">null</span>;</span><br><span class="line"><span class="keyword">throw</span> <span class="literal">undefined</span>;</span><br><span class="line"><span class="keyword">throw</span> &#123;&#125;;</span><br><span class="line"><span class="keyword">throw</span> <span class="keyword">new</span> <span class="built_in">SyntaxError</span>(<span class="string">"useful error message"</span>);</span><br></pre></td></tr></table></figure>
<p>虽然<code>throw</code>声明中可以包含任何数据类型, 使用内置的异常类型始终是更好的选择. 比如在Firefox浏览器下, 如果抛出的是内置异常类型, 浏览器就会在这些对象上添加一些调试信息, 例如错误所在文件名及行号.</p>
<p>举个例子, 你在程序中进行了除法操作, 但是被除数却是0, 这时结果就会是<code>Infinity</code>(原文是<code>NaN</code>, 但是现在是<code>Infinity</code>, 应该是新标准). 这种情况下, 调试起来就会很困难. 如果在被除数是0的情况下抛出异常就能使调试变得容易:</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">if</span> (denominator === <span class="number">0</span>)</span><br><span class="line">  <span class="keyword">throw</span> <span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">"Attempted division by zero!"</span>);</span><br><span class="line"><span class="comment">// 更加合适的错误类型: RangeError: </span></span><br><span class="line"></span><br><span class="line"><span class="keyword">if</span> (denominator === <span class="number">0</span>)</span><br><span class="line">  <span class="keyword">throw</span> <span class="keyword">new</span> <span class="built_in">RangeError</span>(<span class="string">"Attempted division by zero!"</span>);</span><br></pre></td></tr></table></figure>
<h2 id="自定义异常对象"><a href="#自定义异常对象" class="headerlink" title="自定义异常对象"></a>自定义异常对象</h2><p>处理自定义错误信息之外, 我们还能通过extend <code>Error</code>类型自定义错误对象(继承<code>Error</code>), 然后像使用其他内置异常类型一样使用自定义的错误对象.</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// 创建自定义对象</span></span><br><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">DivisionByZeroError</span>(<span class="params">message</span>) </span>&#123;</span><br><span class="line">  <span class="keyword">this</span>.name = <span class="string">"DivisionByZeroError"</span>;</span><br><span class="line">  <span class="keyword">this</span>.message = (message || <span class="string">""</span>);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="comment">// 实现继承</span></span><br><span class="line">DivisionByZeroError.prototype = <span class="keyword">new</span> <span class="built_in">Error</span>();</span><br><span class="line">DivisionByZeroError.prototype.constructor = DivisionByZeroError;</span><br></pre></td></tr></table></figure>
<h2 id="Resources"><a href="#Resources" class="headerlink" title="Resources"></a>Resources</h2><ul>
<li><a href="https://www.sitepoint.com/exceptional-exception-handling-in-javascript/" target="_blank" rel="noopener">Exceptional Exception Handling in JavaScript</a></li>
<li><a href="https://blog.sentry.io/2016/05/17/what-is-script-error" target="_blank" rel="noopener">What the heck is “Script error”?</a></li>
<li><a href="https://www.sitepoint.com/proper-error-handling-javascript/" target="_blank" rel="noopener">Proper Error Handling JavaScript</a></li>
<li><a href="https://blog.sentry.io/2016/01/04/client-javascript-reporting-window-onerror.html" target="_blank" rel="noopener">Capture and report JavaScript errors with window.onerror</a></li>
</ul>
</div></article></div></main><footer><div class="paginator"><a href="/posts/2018/01/02/iterators-and-the-for-of-loop/" class="prev">PREV</a><a href="/posts/2017/09/12/code-snippets/" class="next">NEXT</a></div><div class="copyright"><p>© 2019 - 2023 <a href="https://icyfish.github.io/posts">Fish</a>, powered by <a href="https://hexo.io/" target="_blank">Hexo</a> and <a href="https://github.com/pinggod/hexo-theme-apollo" target="_blank">hexo-theme-apollo</a>.</p></div></footer></div><script async src="//cdn.bootcss.com/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML" integrity="sha384-crwIf/BuaWM9rM65iM+dWFldgQ1Un8jWZMuh3puxb8TOY9+linwLoI7ZHZT+aekW" crossorigin="anonymous"></script></body></html>